CREATE TABLE IF NOT EXISTS `apiweb`.`web` (
  `ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `CIUDAD` VARCHAR(45) NULL,
  `CORREO ELECTRONICO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB